application:
  name: naming-service
spring:
  cloud:
    loadbalancer:
      enabled: false
server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/
  instance:
    hostname: naming-service
    prefer-ip-address: false
    