application:
  name: naming-service
spring:
  cloud:
    loadbalancer:
      enabled: false

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: naming-service
    prefer-ip-address: false
    