spring:
  application:
    name: cloud-config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/hgrodriguez91/WasteManager
          clone-on-start: true
server:
  port: 8888