server:
  port: ${SERVER_PORT:8081}
spring:
  cloud:
    config:
      profile: dev

eureka:
  instance:
    instance-id: ${spring.application.name:waste-manager-service}-${random.uuid}
  client:
    service-url:
      default-zone: http://${EUREKA_SERVER:localhost}:8761

